name: CI of java along with upload and download the artifact
on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the java code
       uses: actions/checkout@v5.0.0
     
     - name: Setup java
       uses: actions/setup-java@v5.0.0
       with:
         java-version: 17 # optional. The Java version to set up.
         distribution: microsoft # Java distribution. See the list of supported distributions in README file

     - name: Build the java appln
       run: mvn --batch-mode --update-snapshots verify

     - name: Upload the build artifact
       uses: actions/upload-artifact@v4.6.2
       with:
         name: myartifact  # Artifact name. Give anything
         path: target/*.jar   # A file, directory or wildcard pattern that describes what to upload

     - name: Download the build artifact
       uses: actions/download-artifact@v5.0.0
       with:
         name: myartifact  # Name of the artifact to download. optional. If unspecified, all artifacts for the run are downloaded.
         path: sonali # optional. Destination path where to store the downloaded artifact..
        #  github-token: # This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
        #  repository: # optional, default is ${{ github.repository }}.  # <repositoryOwner/repositoryName>. If github-token is specified, this is the repository that artifacts will be downloaded from.
        #  run-id: # optional, default is ${{ github.run_id }}. The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
    
     - name: Verify whether the build artifact are downloaded
       run: ls -lrt && ls sonali    
    
         
